### ISSUE TITLE
 /usr/local/openldap/sbin/slaptest: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ddiawara** [ltb-project/ansible-role-ldaptoolbox-openldap#4]
hello i have this error 

STDOUT:

+ systemctl stop slapd.service
++ mktemp
+ TMP_SLAPD_CONF=/tmp/tmp.ywX85fnP48
+ trap 'rm -f "$TMP_SLAPD_CONF"' EXIT
+ cp /usr/local/openldap/etc/openldap/slapd.conf /tmp/tmp.ywX85fnP48
+ test /srv/ldap/somfy '!=' /usr/local/openldap/var/openldap-data -a '!' -d /srv/ldap/somfy
+ sed -i 's#^directory\s.*#directory "/srv/ldap/somfy"#' /tmp/tmp.ywX85fnP48
+ cat
+ mkdir --mode=0750 -p /usr/local/openldap/etc/openldap/slapd.d
+ /usr/local/openldap/sbin/slaptest -f /tmp/tmp.ywX85fnP48 -F /usr/local/openldap/etc/openldap/slapd.d
/usr/local/openldap/sbin/slaptest: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
+ rm -f /tmp/tmp.ywX85fnP48

**Comment by artlog** [comment]
@ddiawara what distribution are you using ? It seems you don't have libssl1.1 installed on your system.
Can you provide more context ?

**Comment by davidcoutadeur** [comment]
Hello, please use the mailing lists: https://www.ltb-project.org/contact.html if you need help about LTB projects.

The issue you raised could just be a bad usage of OpenLDAP-LTB package or role.
If you suspect a bug, you can open an issue, but take care to give all contextual information.
