### ISSUE TITLE
add support for rpm based targets

### ISSUE THREAD

**Issue by artlog** [ltb-project/ansible-role-ldaptoolbox-openldap#7]
Current role is only for debian based targets.

Support for RedHat/CentOs/Rocky with rpm would be great.

**Comment by artlog** [comment]
taking a look

**Comment by artlog** [comment]
This is covered by https://github.com/ltb-project/ansible-role-ldaptoolbox-openldap/pull/8

**Comment by davidcoutadeur** [comment]
A new branch (rpm_only) + a new pull request will be dedicated to this feature, as the current one (#8) mix multiple features.

**Comment by davidcoutadeur** [comment]
Done in https://github.com/ltb-project/ansible-role-ldaptoolbox-openldap/pull/12
